spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql:  true # System.out을 통해 찍는 것이므로 사용 X. 아래 'org.hibernate.SQL: debug'가 logger를 통해 찍음
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace