spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # create(RUN할 때 테이블 초기화)
    properties:
      hibernate:
#        show_sql:  true # System.out을 통해 찍는 것이므로 사용 X. 아래 'org.hibernate.SQL: debug'가 logger를 통해 찍음
        format_sql: true
        default_batch_fetch_size: 100 # in query의 개수를 몇 개로 할 건지 정한다.
#    open-in-view: false # OSIV 옵션 (default : true)

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace